disp('sDaDa  Copyright (C) 2018 ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE,')
disp('Switzerland, Laboratory of Experimental Biophysics')
disp('This program comes with ABSOLUTELY NO WARRANTY; for details see LICENSE.txt.')
disp('This is free software, and you are welcome to redistribute it')
disp('under certain conditions; see LICENSE.TXT for details.')